reference_fits: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/data/doublecb/RawYields/mass_fits.root               # file with central values
    
inputs:
  data: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/data/doublecb/Projections/projections.root
  template:
    file: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/MC/doublecb/Projections/wo_bdt/dplus_corr_bkg_template.root
    hist_name: 'h_mass_{pt_min}_{pt_max}'    # can use also pt_min, pt_max, cent_min, cent_max to format name. pt variables are multiplied by 10 to avoid floating point issues
  cutset: '/home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/configs/cutset.yml'

output:
  dir: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Systematics/RawYields/vsMult/norm_vars           # output directory
  save_all_fits: true                                   # whether to save all fits figures
  dir_fits: fits                                        # append to output_dir
  formats: [pdf, png]                                   # save figures in these formats
  suffix: ''                                            # suffix for output files

max_workers: 15
batch_size: 120 # multiple of max_workers

multitrial:
    pt_bins: [0, 1, 2]                                       # list of pt bins, set null if you want to keep them all
    mins: [1.77, 1.75, 1.79]                           # lower fit limit
    maxs: [2.08, 2.1, 2.12]                             # upper fit limit
    rebins: [2, 4]                                   # rebinning
    sgn_funcs: [["doublecbsymm", "doublecbsymm"], ["gaussian", "gaussian"]]                   # signal functions
    par_init_limit:
      - # First set of signal functions
        - sigma:
            init: [0.005, 0.01, 0.01, 0.02, 0.02, 0.02]
            min: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
            max: [0.013, 0.013, 0.02, 0.03, 0.04, 0.04]
            fix_to_config_value: [false, false, false, false, false, false]
            fix_to_file: [false, false, false, false, false, false]
          alpha:
            init: [1.40, 1.22, 1.39, 1.62, 1.59, 1.43]
            min: [0., 0., 0., 0., 0.5, 0.75]
            max: [5., 5., 5., 5., 5., 5.]
            fix_to_config_value: [false, false, false, false, false, false]
            fix_to_file: [true, true, true, true, true, true]
          n:
            init: [23.75, 39.00, 5.67, 3.00, 3.07, 3.08]
            min: [3, 3, 3, 3, 3, 3]
            max: [100., 100., 100., 100., 100., 100.]
            fix_to_config_value: [false, false, false, false, false, false]
            fix_to_file: [true, true, true, true, true, true]
        - sigma:
            init: [0.005, 0.01, 0.015, 0.02, 0.02, 0.02]
            min: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
            max: [0.013, 0.013, 0.025, 0.03, 0.04, 0.04]
            fix_to_config_value: [false, false, false, false, false, false]
            fix_to_file: [false, false, false, false, false, false]
          alpha:
            init: [1.48, 1.39, 1.38, 1.34, 1.37, 1.27]
            min: [0., 0., 0., 0., 0.5, 0.75]
            max: [5., 5., 5., 5., 5., 5.]
            fix_to_config_value: [false, false, false, false, false, false]
            fix_to_file: [true, true, true, true, true, true]
          n:
            init: [87.14, 7.17, 6.41, 9.38, 17.03, 19.76]
            min: [3, 3, 3, 3, 3, 3]
            max: [100., 100., 100., 100., 100., 100.]
            fix_to_config_value: [false, false, false, false, false, false]
            fix_to_file: [true, true, true, true, true, true]
      - # Second set of signal functions
        - sigma:
            init: [0.005, 0.01, 0.01, 0.02, 0.02, 0.02]
            min: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
            max: [0.013, 0.013, 0.02, 0.03, 0.04, 0.04]
            fix_to_config_value: [false, false, false, false, false, false]
            fix_to_file: [false, false, false, false, false, false]
        - sigma:
            init: [0.005, 0.01, 0.015, 0.02, 0.02, 0.02]
            min: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
            max: [0.013, 0.013, 0.025, 0.03, 0.04, 0.04]
            fix_to_config_value: [false, false, false, false, false, false]
            fix_to_file: [false, false, false, false, false, false]

    file_for_params_fix: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/MC/doublecb/RawYields/mass_fits.root # path to root file. If null, no file is used
    suffix_hist_for_params_fix: "_0_100" # "" for no centrality selection, can also use cent_min, cent_max to format name
    bkg_funcs: [["chebpol2"], ["expo"]]   # bkg functions
    sigma_option: [
        free, fixed, fixed_plus_unc, fixed_minus_unc # (wrt MB)
    ]                                                   # free, fixed, fixed_plus_unc, fixed_minus_unc, fixed_plus_XX_perc, fixed_minus_XX_perc
    fix_ratio_ds_dplus_width: [0.9, 0.85, 0.8]                     # fix ratio of Ds to D+ width
    backgrounds:
      - name: $\mathrm{D^{+}}\rightarrow K^{-}\pi^{+}\pi^{+}$
        file_norm: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/MC/doublecb/Projections/w_bdt/dplus_bkg.root # with BDT selections (for normalisation)
        norm_hist_name: 'h_mass_{pt_min}_{pt_max}_cent_0_100'
        template_file: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/MC/doublecb/Projections/wo_bdt/dplus_corr_bkg_template.root
        template_hist_name: 'h_mass_{pt_min}_{pt_max}' # can use also pt_min, pt_max, cent_min, cent_max to format name. pt variables are multiplied by 10 to avoid floating point issues
        br:
          pdg: 0.0938 # K pi pi
          simulations: 0.4853 # 0.4263 + 0.059 (K pi pi + K0* pi)
    signal:
      file_norm: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/MC/doublecb/Projections/w_bdt/dplus.root # str or list of str
      hist_name: 'h_mass_{pt_min}_{pt_max}_cent_0_100' # can use also pt_min, pt_max, cent_min, cent_max to format name. pt variables are multiplied by 10 to avoid floating point issues
      br:
        pdg: 0.00269
        simulations: 0.4263
    mean: [free]                                        # free, fixed, fixed_plus_unc, fixed_minus_unc, fixed_plus_XX_perc, fixed_minus_XX_perc
    bincounting_nsigma: [2,3,5]                              # nsigmas for bin counting raw yield extraction
    quality_selections:
      chi2: 10
      significance: 4
      ds_nsigma: 1.                                     # maximum distance in sigma uncertainty units from the central sigma for Ds candidates          

files_to_draw: 
  mb: null                                              # overrides the output_dir + suffix for getting the files to draw
  cent: null                                            # overrides the output_dir + suffix for getting the files to draw

assigned_syst: [[0.1, 0.1, 0.1], [0.1, 0.1, 0.1], [0.1, 0.1, 0.1]]                               # assigned systematic uncertainties