cutvars:
  InvMass:
    axisnum: 0
    name: inv_mass
  ML_output_Bkg:
    axisnum: 3
    max:
    - 0.0901
    - 0.36010000000000003
    - 0.36010000000000003
    - 0.4501
    - 0.4501
    - 0.4501
    - 0.4501
    - 0.5401
    - 0.5401
    - 0.36010000000000003
    - 0.5401
    - 0.5401
    - 0.5401
    min:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    name: ML_output_Bkg
  ML_output_Prompt:
    axisnum: 4
    max:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    min:
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    name: ML_output_Prompt
  Pt:
    axisnum: 1
    max:
    - 1.5
    - 2
    - 2.5
    - 3
    - 3.5
    - 4
    - 4.5
    - 5
    - 5.5
    - 6
    - 8
    - 12
    - 24
    min:
    - 1
    - 1.5
    - 2
    - 2.5
    - 3
    - 3.5
    - 4
    - 4.5
    - 5
    - 5.5
    - 6
    - 8
    - 12
    name: fPt
