cutvars:
  InvMass:
    axisnum: 0
    name: inv_mass
  ML_output_Bkg:
    axisnum: 3
    max:
    - 0.30000000000000004
    - 0.6000000000000001
    - 0.6000000000000001
    - 0.7
    - 0.7
    - 0.7
    - 0.7
    - 0.8
    - 0.8
    - 0.8999999999999999
    - 0.8
    - 0.8
    - 0.8
    min:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    name: ML_output_Bkg
  ML_output_Prompt:
    axisnum: 4
    max:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    min:
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    name: ML_output_Prompt
  Pt:
    axisnum: 1
    max:
    - 1.5
    - 2
    - 2.5
    - 3
    - 3.5
    - 4
    - 4.5
    - 5
    - 5.5
    - 6
    - 8
    - 12
    - 24
    min:
    - 1
    - 1.5
    - 2
    - 2.5
    - 3
    - 3.5
    - 4
    - 4.5
    - 5
    - 5.5
    - 6
    - 8
    - 12
    name: fPt
