inputs:
  efficiency: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Efficiency/efficiency/default/efficiency_LHC25a5.root
  cutset: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/configs/cutset.yml

data: pp # pp or pbpb (use pp data and TAMU RAA predictions or PbPb data)

fit_function: powerlaw # tsallis or powerlaw

cent:
  min: 0
  max: 10

output: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/FD_Fraction/fc_method/DsPromptNonPrompt_Yield_pp5TeV_Run2_010_tsallis.root