inputs:
    directory: /home/fchinu/Run3/Ds_pp_13TeV/Systematics/BDT
    commonfilenames:
        rawyield: RawYields/RawYields_data_ML__
        efficiency: Efficiency_LHC24d3a/Efficiency__ML__
        prompt_frac_ds: Prompt_Fraction/PromptFracDs__ML__
        prompt_frac_dplus: Prompt_Fraction/PromptFracDplus__ML__
        ratios: Ratios_LHC24d3a/Ratio__ML__
    cutsets: [  
            outBkg_pos00_outPrompt_pos00,
            outBkg_pos00_outPrompt_neg01,
            outBkg_pos00_outPrompt_neg02,
            outBkg_pos00_outPrompt_neg03,
            outBkg_pos00_outPrompt_pos01,
            outBkg_pos00_outPrompt_pos02,
            outBkg_pos00_outPrompt_pos03,
            outBkg_neg03_outPrompt_neg01,
            outBkg_neg03_outPrompt_neg02,
            outBkg_neg03_outPrompt_neg03,
            outBkg_neg03_outPrompt_pos00,
            outBkg_neg03_outPrompt_pos01,
            outBkg_neg03_outPrompt_pos02,
            outBkg_neg03_outPrompt_pos03,
            outBkg_neg02_outPrompt_neg01,
            outBkg_neg02_outPrompt_neg02,
            outBkg_neg02_outPrompt_neg03,
            outBkg_neg02_outPrompt_pos00,
            outBkg_neg02_outPrompt_pos01,
            outBkg_neg02_outPrompt_pos02,
            outBkg_neg02_outPrompt_pos03,
            outBkg_neg01_outPrompt_neg01,
            outBkg_neg01_outPrompt_neg02,
            outBkg_neg01_outPrompt_neg03,
            outBkg_neg01_outPrompt_pos00,
            outBkg_neg01_outPrompt_pos01,
            outBkg_neg01_outPrompt_pos02,
            outBkg_neg01_outPrompt_pos03,
            outBkg_pos01_outPrompt_neg01,
            outBkg_pos01_outPrompt_neg02,
            outBkg_pos01_outPrompt_neg03,
            outBkg_pos01_outPrompt_pos00,
            outBkg_pos01_outPrompt_pos01,
            outBkg_pos01_outPrompt_pos02,
            outBkg_pos01_outPrompt_pos03,
            outBkg_pos02_outPrompt_neg01,
            outBkg_pos02_outPrompt_neg02,
            outBkg_pos02_outPrompt_neg03,
            outBkg_pos02_outPrompt_pos00,
            outBkg_pos02_outPrompt_pos01,
            outBkg_pos02_outPrompt_pos02,
            outBkg_pos02_outPrompt_pos03,
            outBkg_pos03_outPrompt_neg01,
            outBkg_pos03_outPrompt_neg02,
            outBkg_pos03_outPrompt_neg03,
            outBkg_pos03_outPrompt_pos00,
            outBkg_pos03_outPrompt_pos01,
            outBkg_pos03_outPrompt_pos02,
            outBkg_pos03_outPrompt_pos03
        ] # the first one must be the default

outfilename: /home/fchinu/Run3/Ds_pp_13TeV/Systematics/BDT/output/BDT_syst

quality:
    maxchisquare: 2.
    minsignif: 3.
    minrelsignif: 0.5
    minreleff: 0.6
    maxreleff: 2.5
    fillthrreleff: 0.005

plots:
    plotrelativevar: 1 # 0 -> false, 1 -> true
    relassignedsyst: [0.10, 0.05, 0.03, 0.03, 0.02, 0.02, 0.01, 0.01, 0.01, 0.02, 0.02, 0.02, 0.02, 0.02] # list of values to be plotted, null if you don't want to plot it
  