particles: ["Ds", "Dplus"]
origins: ["Prompt", "NonPrompt"]

inputs:
  mc: "/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/MC/Train273656/AnalysisResults_LHC24g5.root"
  data: "/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train271875/AnalysisResults_LHC22o_pass7.root"
  task_names: ["hf-task-ds", "hf-task-ds_WithNPV"]
  histos_names: ["hNPvContribCands", "hNPvContribCandsInSignalRegionDs", "hNPvContribCandsInSignalRegionDplus"]
  histos_names_as_data_only: ["hNPvContribAll"] # We do not save the histogram for the different particle species (as it is the same for all)
  

output:
  dir: "/home/fchinu/Run3/Ds_pp_13TeV/Efficiency/VsMult"
  suffix: ["FT0M", "NTracksPV"]