particles: ["Ds", "Dplus"]
origins: ["Prompt", "NonPrompt"]

inputs:
  mc: "/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/MC/Train365623/AnalysisResults_LHC24d2b_0.root"
  data: "/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train290606/AnalysisResults_LHC23_pass4_0.root"
  task_names: ["hf-task-ds", "hf-task-ds_WithNPV"]

  histos_names: ["hNPvContribCands", "hNPvContribCandsInSignalRegionDs", "hNPvContribCandsInSignalRegionDplus"]
  histos_names_as_data_only: ["hNPvContribAll"] # We do not save the histogram for the different particle species (as it is the same for all)
  

output:
  dir: "/home/fchinu/Run3/Ds_pp_13TeV/Efficiency/VsMult"
  suffix: ["LHC24d3b_new_model_swap_prongs"]