input_data:
  - file: '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train197246/LHC22o_pass6_small.parquet'
    histogram: 'Data'
    dataframe_column: 'fAbsCos3PiK'               # Draw the histogram of the column1 of the parquet file
    selections: '4 < fPt < 6'
    color: 'kTeal-6'
    marker_style: 'kOpenCircle'
    marker_size: 1.0
    line_width: 2
    line_style: null
    scale_factor: 1.0
    fill_style: 0
    fill_color: 'kTeal-6'
    fill_alpha: 0.5
    normalize: true
    draw_option: 'hist'
  - file: '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/MC/Train213175/LHC24d3a_NonPromptDs.parquet'
    histogram: 'FD'
    dataframe_column: 'fAbsCos3PiK'               # Draw the histogram of the column1 of the parquet file
    selections: '4 < fPt < 6'
    color: 'kOrange-3'
    marker_style: 'kOpenCircle'
    marker_size: 1.0
    line_width: 2
    line_style: null
    scale_factor: 1.0
    fill_style: 3154
    fill_color: 'kOrange-3'
    fill_alpha: 1
    normalize: true
    draw_option: 'hist'
  - file: '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/MC/Train213175/LHC24d3a_PromptDs.parquet'
    histogram: 'Prompt'
    dataframe_column: 'fAbsCos3PiK'               # Draw the histogram of the column1 of the parquet file
    selections: '4 < fPt < 6'
    color: 'kBlue+3'
    marker_style: 'kOpenCircle'
    marker_size: 1.0
    line_width: 2
    line_style: null
    scale_factor: 1.0
    fill_style: 3145
    fill_color: 'kBlue+3'
    fill_alpha: 1
    normalize: true
    draw_option: 'hist'

canvas:
  width: 800
  height: 600
  title: ''
  same_bins: True
  margin:
    left: 0.12
    right: 0.05
    top: 0.05
    bottom: 0.12
  axes:
    x:
      title: 
        name: '|cos^{3}#theta_{#piK}|'
        size: 0.05
        offset: 1
      labels:
        size: 0.045
        offset: 0.01
      range: [0, 1]
      log_scale: false
    y:
      title: 
        name: 'Normalised counts'
        size: 0.05
        offset: 1.2
      labels:
        size: 0.045
        offset: 0.01
      range: [6.e-4, 3.e-1]
      log_scale: true

text:
  - content: 'This Thesis'
    x: 0.37
    y: 0.85
    size: 0.07
    font: 42
  - content: 'pp, #sqrt{s} = 13.6 TeV'
    x: 0.375
    y: 0.78
    size: 0.065
    font: 42
  - content: '4 < #it{p}_{T} < 6 GeV/#it{c}'
    x: 0.375
    y: 0.71
    size: 0.065
    font: 42

legend:
  draw: true
  x1: 0.37
  y1: 0.39
  x2: 0.67
  y2: 0.69
  size: 0.065
  entries:
    - histogram: 'Data'
      label: 'Data'
      style: 'f'
    - histogram: 'Prompt'
      label: 'Prompt D_{s}^{+}'
      style: 'f'
    - histogram: 'FD'
      label: 'Feed#font[122]{-}down D_{s}^{+}'
      style: 'f'

horizontal_line:
  draw: false
  height: 50
  line_color: ROOT.kBlack  # Use appropriate ROOT color constant
  line_style: 9  # Use appropriate ROOT line style constant


output_file: '/home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/AbsCos3PiK.pdf'
