input_data:
  - file: '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Train162788/LHC22o_Train162788.parquet'
    histogram: 'Data'
    dataframe_column: 'fDeltaMassPhi'               # Draw the histogram of the column1 of the parquet file
    selections: '4 < fPt < 6 and abs(fDeltaMassPhi)<0.02'
    color: 'kTeal-6'
    marker_style: 'kOpenCircle'
    marker_size: 1.0
    line_width: 2
    scale_factor: 1.0
    fill_style: 0
    fill_color: 'kTeal-6'
    fill_alpha: 0.5
    normalize: true
    draw_option: 'hist'
  - file: '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Train165701/Merged_LHC22b1a_Train165701_DsFD.parquet'
    histogram: 'FD'
    dataframe_column: 'fDeltaMassPhi'               # Draw the histogram of the column1 of the parquet file
    selections: '4 < fPt < 6 and abs(fDeltaMassPhi)<0.02'
    color: 'kOrange-3'
    marker_style: 'kOpenCircle'
    marker_size: 1.0
    line_width: 2
    scale_factor: 1.0
    fill_style: 3154
    fill_color: 'kOrange-3'
    fill_alpha: 1
    normalize: true
    draw_option: 'hist'
  - file: '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Train165701/Merged_LHC22b1a_Train165701_DsPrompt.parquet'
    histogram: 'Prompt'
    dataframe_column: 'fDeltaMassPhi'               # Draw the histogram of the column1 of the parquet file
    selections: '4 < fPt < 6 and abs(fDeltaMassPhi)<0.02'
    color: 'kBlue+3'
    marker_style: 'kOpenCircle'
    marker_size: 1.0
    line_width: 2
    scale_factor: 1.0
    fill_style: 3145
    fill_color: 'kBlue+3'
    fill_alpha: 1
    normalize: true
    draw_option: 'hist'

canvas:
  width: 800
  height: 600
  title: ''
  margin:
    left: 0.12
    right: 0.05
    top: 0.05
    bottom: 0.12
  axes:
    x:
      title: 
        name: '#DeltaM_{KK} (GeV/c^{2})'
        size: 0.05
        offset: 1
      labels:
        size: 0.045
        offset: 0.01
      range: [0, 0.02]
      log_scale: false
    y:
      title: 
        name: 'Normalised counts'
        size: 0.05
        offset: 1.2
      labels:
        size: 0.045
        offset: 0.01
      range: [3.e-4, 0.5]
      log_scale: true

text:
  - content: 'This Thesis'
    x: 0.15
    y: 0.85
    size: 0.07
    font: 42
  - content: 'pp, #sqrt{s} = 13.6 TeV'
    x: 0.155
    y: 0.78
    size: 0.065
    font: 42
  - content: '4 < #it{p}_{T} < 6 GeV/#it{c}'
    x: 0.155
    y: 0.71
    size: 0.065
    font: 42

legend:
  draw: true
  x1: 0.55
  y1: 0.615
  x2: 0.85
  y2: 0.915
  size: 0.065
  entries:
    - histogram: 'Data'
      label: 'Data'
      style: 'f'
    - histogram: 'Prompt'
      label: 'Prompt D_{s}^{+}'
      style: 'f'
    - histogram: 'FD'
      label: 'Feed#font[122]{-}down D_{s}^{+}'
      style: 'f'

horizontal_line:
  draw: false
  height: 50
  line_color: ROOT.kBlack  # Use appropriate ROOT color constant
  line_style: 9  # Use appropriate ROOT line style constant


output_file: '/home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/DeltaMassKK.pdf'
