input_data:
  - file: '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/MC/Train213175/LHC24d3a_NonPromptDs.parquet'
    histogram: 'FD'
    dataframe_column: 'fAbsCos3PiK'               # Draw the histogram of the column1 of the parquet file
    selections: '4 < fPt < 6'
    color: 'kAzure-3'
    marker_style: 'kOpenCircle'
    marker_size: 1.0
    line_width: 2
    line_style: null
    scale_factor: 1.0
    fill_style: 0
    fill_color: 'kAzure-3'
    fill_alpha: 0.5
    normalize: true
    draw_option: 'hist'
  - file: '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train197246/LHC22o_pass6_small.parquet'
    histogram: 'Data'
    dataframe_column: 'fAbsCos3PiK'               # Draw the histogram of the column1 of the parquet file
    selections: '4 < fPt < 6'
    color: 'kTeal-6'
    marker_style: 'kOpenCircle'
    marker_size: 1.0
    line_width: 2
    line_style: null
    scale_factor: 1.0
    fill_style: 0
    fill_color: 'kTeal-6'
    fill_alpha: 0.5
    normalize: true
    draw_option: 'hist'
  - file: '/home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/MC/Train213175/LHC24d3a_PromptDs.parquet'
    histogram: 'Prompt'
    dataframe_column: 'fAbsCos3PiK'               # Draw the histogram of the column1 of the parquet file
    selections: '4 < fPt < 6'
    color: 'kRed-7'
    marker_style: 'kOpenCircle'
    marker_size: 1.0
    line_width: 2
    line_style: null
    scale_factor: 1.0
    fill_style: 0
    fill_color: 'kRed-7'
    fill_alpha: 0.5
    normalize: true
    draw_option: 'hist'

canvas:
  width: 800
  height: 600
  title: ''
  same_bins: True
  margin:
    left: 0.12
    right: 0.05
    top: 0.05
    bottom: 0.12
  axes:
    x:
      title: 
        name: '|cos^{3}#theta_{#piK}|'
        size: 0.05
        offset: 1
      labels:
        size: 0.045
        offset: 0.01
      range: [0, 1]
      log_scale: false
      ticksx: false
    y:
      title: 
        name: 'Normalised counts'
        size: 0.05
        offset: 1.2
      labels:
        size: 0.045
        offset: 0.01
      range: [6.e-4, 6.e-1]
      log_scale: true
      ticksy: false

text:
  - content: 'This Thesis'
    x: 0.26
    y: 0.85
    size: 0.07
    font: 42
  - content: 'pp, #sqrt{s} = 13.6 TeV'
    x: 0.265
    y: 0.78
    size: 0.065
    font: 42
  - content: '4 < #it{p}_{T} < 6 GeV/#it{c}'
    x: 0.265
    y: 0.71
    size: 0.065
    font: 42

legend:
  draw: true
  x1: 0.25
  y1: 0.35
  x2: 0.55
  y2: 0.65
  size: 0.065
  entries:
    - histogram: 'Data'
      label: '#splitline{#lower[1]{Background}}{#lower[-0.1]{(data, sidebands)}}'
      style: 'f'
    - histogram: 'Prompt'
      label: 'Prompt D_{#lower[-0.2]{s}}^{+} (MC)'
      style: 'f'
    - histogram: 'FD'
      label: 'Non#font[122]{-}prompt D_{#lower[-0.2]{s}}^{+} (MC)'
      style: 'f'

horizontal_line:
  draw: false
  height: 50
  line_color: ROOT.kBlack  # Use appropriate ROOT color constant
  line_style: 9  # Use appropriate ROOT line style constant


output_file: '/home/fchinu/Run3/Ds_pp_13TeV/Figures/Variables_Distributions/AbsCos3PiK.pdf'
