pp13TeVPrompt:
    Particle: 'Ds'
    FixSigma: True
    SigmaFile: '/home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/Data/LHC22o_pass7/VsMult/RawYields_Data_Cent_0_100.root'
    SigmaMultFactor: 1.
    FixMean: 0
    MeanFile: ''
    CentMin: [0]  
    CentMax: [100]
    PtMin: [0, 2, 4, 6, 8, 12] 
    PtMax: [2, 4, 6, 8, 12, 24]
    MassMin: [1.75, 1.75, 1.73, 1.73, 1.73, 1.73]    
    MassMax: [2.1,   2.1, 2.15, 2.15, 2.15, 2.15]
    Rebin: [2, 2, 2, 2, 4, 4]
    InclSecPeak: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    SigmaSecPeak: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.015, 0.015, 0.015, 0.015, 0.013,  0.013, 0.015, 0.02, 0.02]
    FixSigmaSecPeak: [false, false, false, false, true, true]
    SigmaFileSecPeak: ''
    SigmaMultFactorSecPeak: 0.83
    SigmaRatioSecPeakFile: null
    TemplateFile: /home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/Data/LHC22o_pass7/VsMult/DplusForTemplateHistos_Train165702.root
    FixSigmaRatioSecPeak: 0
    FixSigmaToFirstPeak: false
    UseLikelihood: 1
    BkgFunc: ['chebpol2', 'chebpol2', 'chebpol2', 'chebpol2', 'chebpol2', 'chebpol2', 'chebpol2', 'chebpol2', 'chebpol2', 'chebpol2', 'chebpol2', 'chebpol2', 'chebpol2', 'chebpol2', 'chebpol2']
    SgnFunc: ['kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus']
    FixSigmaRatio: 0 # used only if SgnFunc = k2GausSigmaRatioPar
    SigmaRatioFile: ""
    BoundMean: 0 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]
    EnableRef: false
