inputs:
    dirname: null # leave null if not common for all input files
    filenames: [ /home/fchinu/Run3/Ds_pp_13TeV/Efficiency/EfficienciesKKPi.root,
                /home/fchinu/Run3/Ds_pp_13TeV/Efficiency/EfficienciesKKPi.root,
                /home/fchinu/Run3/Ds_pp_13TeV/Efficiency/EfficienciesPiKK.root,
                /home/fchinu/Run3/Ds_pp_13TeV/Efficiency/EfficienciesPiKK.root
                ]

    objectnames: [RecoEff_DsPrompt,RecoEff_DplusPrompt,RecoEff_DsPrompt,RecoEff_DplusPrompt] # can be either histograms of graphs or a mix of them; they will be drawn in the current order

output: 
    filename: /home/fchinu/Run3/Ds_pp_13TeV/Efficiency/KKPi_PiKK_Reco_eff_diff # with path and w/o extension
    extensions: [pdf,png] # possibilities: pdf, eps, png, root

options:
    ROOTobject: [TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1] # TH1 or TGraph: no need to specify TH1F, TH1D or TGraphErrors, TGraphAsymmErrors
    scale: [1,1,1,1]
    lambdaParams: [1., 1., 1., 1., 1., 1., 1., 1., 1.] # counts -> (counts - 1) * lambda + 1
    normalize: [false, false, false, false, false, false, false, false, false] # divide histogram by its area
    colors: [kTeal-7,kAzure+3, kRed, kOrange-3]
    markers: [kFullCircle,kFullSquare,kFullCircle,kFullSquare]
    markersize: 2.5
    linewidth: 1
    fillstyle: [1,1,1,1]
    fillalpha: [1,1,1,1]
    drawopt: [e, e, e, e, e, e, e, e, e]
    
    ratio: 
        enable: true
        uncertainties:
            enable: true
            corr: false
        displayRMS: true

    errcomp: # comparison of uncertainties
        enable: false
        relative: false

    legend:
        avoid: false #set true to avoid the legend in the final plot
        xlimits: [0.2, 0.9]
        ylimits: [0.2, 0.5]
        header: null
        titles: ['Reco. Efficiency Ds Prompt KKPi','Reco. Efficiency D+ Prompt KKPi', 'Reco. Efficiency Ds Prompt PiKK','Reco. Efficiency D+ Prompt PiKK']
        options: [lp, lp, lp, lp, lp, lp, lp, lp, lp]
        textsize: 0.045
        ncolumns: 1

    canvas:
        width: 2000
        heigth: 1000
        xaxistitle: '#it{p}_{T} (GeV/#it{c})'
        yaxistitle: 'Acceptance #times Efficiency'
        xlimits: [0., 24]
        ylimits: [1.e-4, 1]
        ylimitsratio: [0.1, 4]
        ylimitserr: [0., 0.35]
        logy: true
        logx: false
        ratio:
            logy: false
            logx: false
        errcomp:
            logy: false
            logx: false  
