isMC: yes
filename: [ /data/shared/Ds_pp_13TeV/data/AnalysisResultsDs_LHC2016_deghjop_train3629.root,
            /data/shared/Ds_pp_13TeV/data/AnalysisResultsDs_LHC2017_train3631.root,
            /data/shared/Ds_pp_13TeV/data/AnalysisResultsDs_LHC2016_kl_train3630.root,
            /data/shared/Ds_pp_13TeV/data/AnalysisResultsDs_LHC2018_train3635.root
]
dirname: PWGHF_D2H_InvMassDs_Ds_Loose_kINT7
listname: coutputDs_Ds_Loose_kINT7
sparsenameAll: null
sparsenamePrompt: fnSparseReco_fromC
sparsenameFD: fnSparseReco_fromB
sparsenameGenPrompt: fnSparseAcc_fromC
sparsenameGenFD: fnSparseAcc_fromB
enableRef: no #reflection for D0
enableSecPeak: yes
sparsenamePromptSecPeak: fnSparseRecoDplus_fromC
sparsenameFDSecPeak: fnSparseRecoDplus_fromB
sparsenameGenPromptSecPeak: fnSparseAccDplus_fromC
sparsenameGenFDSecPeak: fnSparseAccDplus_fromB
normname: NormalizationCounter
histoevname: hNEvents

#info for trees (files can be different if trees are filtered or with applied ML models)
tree:
    particle: Dplus #needed to define binning for invariant-mass histo
    filenameAll: null #not needed for MC
    filenamePrompt:  [
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt1_1.5/DplusPrompt_pT_1_1.5_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt1.5_2/DplusPrompt_pT_1.5_2_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt2_2.5/DplusPrompt_pT_2_2.5_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt2.5_3/DplusPrompt_pT_2.5_3_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt3_3.5/DplusPrompt_pT_3_3.5_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt3.5_4/DplusPrompt_pT_3.5_4_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt4_4.5/DplusPrompt_pT_4_4.5_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt4.5_5/DplusPrompt_pT_4.5_5_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt5_5.5/DplusPrompt_pT_5_5.5_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt5.5_6/DplusPrompt_pT_5.5_6_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt6_8/DplusPrompt_pT_6_8_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt8_12/DplusPrompt_pT_8_12_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt12_24/DplusPrompt_pT_12_24_ModelApplied.parquet.gzip
    ]
    filenameFD: [
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt1_1.5/DplusFD_pT_1_1.5_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt1.5_2/DplusFD_pT_1.5_2_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt2_2.5/DplusFD_pT_2_2.5_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt2.5_3/DplusFD_pT_2.5_3_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt3_3.5/DplusFD_pT_3_3.5_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt3.5_4/DplusFD_pT_3.5_4_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt4_4.5/DplusFD_pT_4_4.5_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt4.5_5/DplusFD_pT_4.5_5_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt5_5.5/DplusFD_pT_5_5.5_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt5.5_6/DplusFD_pT_5.5_6_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt6_8/DplusFD_pT_6_8_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt8_12/DplusFD_pT_8_12_ModelApplied.parquet.gzip,
        /home/fchinu/Run3/Ds_pp_13TeV/ML/Application/pt12_24/DplusFD_pT_12_24_ModelApplied.parquet.gzip
    ]
    dirname: null
    treename: null
