inputs:
  names: /home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train252059/LHC22o_AnalysisResults.root # string or list of strings
  sparses: hf-task-ds/Data/hSparseMass
  event_histogram: bc-selection-task/hCounterTVXafterBCcuts

cut_set_file_name: /home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/configs/cutset_pp13TeV_multiplicity.yml

max_workers: 10

output:
  directory: /home/fchinu/Run3/Ds_pp_13TeV/Projections_RawYields/VsMult/Test
  file_names: [
    data.root
  ]

