inputs:
  names: [
    # /home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train279067/AnalysisResults_LHC22o_pass7.root,
    /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Datasets/Data/Train433192/AnalysisResults_LHC23_pass4_0.root
  ] # string or list of strings
  sparses: hf-task-ds/Data/hSparseMass
  event_histogram: lumi-task/hCounterTVXafterBCcuts

cut_set_file_name: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/configs/cutset_pbpb13TeV_multiplicity.yml

max_workers: 10

output:
  directory: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/data
  file_names: [
    # data_LHC22.root,
    data_LHC23_new_ML.root,
  ]
