pp13TeVPrompt:
    Particle: 'Ds'
    FixSigma: False
    SigmaFile: null
    SigmaMultFactor: 1.
    FixMean: 0
    MeanFile: ''
    PtMin: [2.,4.,6.,8.]
    PtMax: [4.,6.,8.,50.]
    MassMin: [1.7, 1.7, 1.7, 1.7, 1.7]    
    MassMax: [2.1, 2.1, 2.1, 2.1, 2.1]
    Rebin: [4, 4, 4, 8, 8]
    InclSecPeak: [1, 1, 1, 1, 1, 1, 1, 1]
    SigmaSecPeak: [0.015, 0.013, 0.015, 0.02, 0.02]
    FixSigmaSecPeak: [False, False, False, True, False]
    SigmaFileSecPeak: ''
    SigmaMultFactorSecPeak: 1.
    FixSigmaToFirstPeak: 0
    UseLikelihood: 1
    BkgFunc: ['kPol2', 'kPol2', 'kPol2', 'kPol2', 'kPol2', 'kPol2', 'kPol2', 'kPol2']
    SgnFunc: ['kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus']
    FixSigmaRatio: 0 # used only if SgnFunc = k2GausSigmaRatioPar
    SigmaRatioFile: ""
    BoundMean: 0 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]
    EnableRef: false
