cutvars: 
    InvMass: 
        axisnum: 0
        name: 'inv_mass'
    Pt: 
        axisnum: 1
        min: [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 8, 12]  #[2.,3.,4.,5.,6.,8.]
        max: [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 8, 12, 24] #[3.,4.,5.,6.,8.,50.]
        name: 'fPt'
    ML_output_Prompt:
        axisnum: 4
        min: [0.05, 0.3, 0.25, 0.2, 0.2, 0.2, 0.25, 0.49, 0.2, 0.25, 0.25, 0.20, 0.25, 0.1]
        max: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
        name: 'ML_output_Prompt'
    ML_output_Bkg:
        axisnum: 3
        min: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        max: [0.05,0.05,0.15,0.25,0.3,0.2,0.2,0.25,0.2,0.2,0.3,0.35,0.65,0.45]
        name: 'ML_output_Bkg'
    #ML_output_Prompt:
    #    axisnum: 999
    #    min: [0.2, 0.2, 0.23, 0.2, 0.2, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    #    max: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
    #    name: 'ML_output_Prompt'
    #ML_output_Bkg:
    #    axisnum: 999
    #    min: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    #    max: [0.01, 0.01, 0.01, 0.01, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2]
    #    name: 'ML_output_Bkg'