cutvars: 
    InvMass: 
        axisnum: 0
        name: 'inv_mass'
    Pt: 
        axisnum: 1
        min: [2.,4.,6.,8.,12.]
        max: [4.,6.,8.,12.,50.]
        name: 'fPt'
    ML_output_Prompt:
        axisnum: 999
        min: [0.2,0.16,0.14,0.15,0.1]
        max: [1.,1.,1.,1.,1.]
        name: 'ML_output_Prompt'
    ML_output_Prompt:
        axisnum: 999
        min: [0,0,0,0,0]
        max: [0.2,0.22,0.37,0.43,0.25]
        name: 'ML_output_Prompt'
