mass: 
    axisnum: 0
    name: 'inv_mass'
pt: 
    axisnum: 1
    min: [2, 2, 6, 10]  #[2.,3.,4.,5.,6.,8.]
    max: [24,6, 10, 24] #[3.,4.,5.,6.,8.,50.]
    name: 'fPt'
cent: 
    axisnum: 2
    min: [0, 0, 30, 50]
    max: [100, 30, 50, 90]
    name: 'cent'
ml_output_prompt:
    axisnum: 4
    min: [0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
    max: [1., 1., 1., 1., 1., 1.]
    name: 'ML_output_Prompt'
ml_output_bkg:
    axisnum: 3
    min: [0., 0., 0., 0., 0., 0.]
    max: [0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
    name: 'ML_output_Bkg'