cutvars:
  Cent:
    axisnum: 2
    max:
    - 100
    min:
    - 0
    name: cent
  InvMass:
    axisnum: 0
    name: inv_mass
  ML_output_Bkg:
    axisnum: 3
    max:
    - 0.05
    - 0.2
    - 0.3
    - 0.45
    - 0.5
    - 0.55
    min:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    name: ML_output_Bkg
  ML_output_FD:
    axisnum: 5
    max:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    min:
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    name: ML_output_FD
  Pt:
    axisnum: 1
    max:
    - 2
    - 4
    - 6
    - 8
    - 12
    - 24
    min:
    - 0
    - 2
    - 4
    - 6
    - 8
    - 12
    name: fPt
