inputs:
  names: [
    # /home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/Data/Train279067/AnalysisResults_LHC22o_pass7.root,
    /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Datasets/Data/Train444799/AnalysisResults_LHC23_pass4_0.root

  ] # string or list of strings
  sparses: hf-task-ds/Data/hSparseMass
  event_histogram: eventselection-run3/luminosity/hCounterTVXafterBCcuts

  cutset: /home/fchinu/Run3/Ds_OO_5TeV/Projections_RawYields/configs/cutset_OO5TeV.yml

max_workers: 10

output:
  directory: /home/fchinu/Run3/Ds_OO_5TeV/Projections_RawYields/data
  file_names: [
    # data_LHC22.root,
    data.root
  ]
