inputs:
  names: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Datasets/MC/Train389985/AnalysisResults_LHC25a5.root # string or list of strings
  sparses: [
    hf-task-ds/Data/hSparseMass,
    hf-task-ds/MC/Ds/Prompt/hSparseMass,
    hf-task-ds/MC/Ds/NonPrompt/hSparseMass,
    hf-task-ds/MC/Dplus/Prompt/hSparseMass,
    hf-task-ds/MC/Dplus/NonPrompt/hSparseMass,
    hf-task-ds/MC/Dplus/Bkg/hSparseMass
  ]
  event_histogram: bc-selection-task/hCounterTVXafterBCcuts

cut_set_file_name: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/configs/cutset_pp13TeV_no_mult_no_bdt_MC.yml

max_workers: 10

output:
  directory: /home/fchinu/Run3/Ds_Dp_ratio_PbPb/Projections_RawYields/MC/LHC25a5/wo_bdt
  file_names: [
    data.root,
    ds_prompt.root,
    ds_nonprompt.root,
    dplus_prompt.root,
    dplus_nonprompt.root,
    dplus_bkg.root
  ]

