mass: 
    axisnum: 0
    name: 'inv_mass'
pt: 
    axisnum: 1
    min: [0.5, 1, 2, 4, 6, 8, 12]  #[2.,3.,4.,5.,6.,8.]
    max: [1, 2, 4, 6, 8, 12, 24] #[3.,4.,5.,6.,8.,50.]
    name: 'fPt'
cent: 
    axisnum: 2
    min: [50, 55, 60, 65, 70, 75, 80]
    max: [55, 60, 65, 70, 75, 80, 90]
    name: 'cent'
ml_output_prompt:
    axisnum: 4
    min: [0.1, 0.1,  0.1, 0.1,  0.1, 0.1,  0.1]
    max: [1., 1., 1., 1., 1., 1., 1.]
    name: 'ML_output_Prompt'
ml_output_bkg:
    axisnum: 3
    min: [0, 0, 0, 0, 0, 0, 0]
    max: [0.01, 0.075,  0.12, 0.15,  0.2, 0.3,  0.5]
    name: 'ML_output_Bkg'